### ISSUE TITLE
[Question] v3.1.1 版本部署 应用发布机各种问题

### ISSUE THREAD

**Issue by jumpuser0001** [jumpserver/jumpserver#10164]
**请描述您的问题.**
win2016纯净，没有安装其他东西

第四次报错我再也找不到解决办法了 寻求技术支持
fatal: [副本远程应用发布机]: FAILED! => {"attempts": 30, "changed": false, "elapsed": 2.1720517999999998, "msg": "Unhandled exception occurred when sending web request. Exception: Unable to connect to the remote server", "status_code": null, "url": "http://localhost:6068/api/health/"}

在找到问题转第三次 （不启用HTTPS也能报错？）
TASK [Download JumpServer Tinker installer (jumpserver)] ***********************
fatal: [副本远程应用发布机]: FAILED! => {"changed": false, "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer.exe", "elapsed": 21.1100416, "msg": "Error downloading 'https://192.168.1.2/download/applets/Tinker_Installer.exe'

找到问题
转第二次
TASK [Sync all remote applets] *************************************************
fatal: [副本远程应用发布机]: FAILED! => {"changed": true, "cmd": "tinkerd install all", "delta": "0:00:01.795148", "end": "2023-04-09 16:01:26.947443", "msg": "non-zero return code", "rc": 1, "start": "2023-04-09 16:01:25.152294", "stderr": "2023/04/10 00:01:26 install all applets failed: 

第一次提示这个
TASK [Install JumpServer Tinker (jumpserver)] **********************************
fatal: [副本远程应用发布机]: FAILED! => {"changed": false, "msg": "unexpected rc from 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART': see rc, stdout, and stderr for more details", "rc": 4, "reboot_required": false, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

教程真的有用么？

**Comment by LeeEirc** [comment]
参考下之前的 [issue](https://github.com/jumpserver/jumpserver/issues/10005)

**Comment by DaiYuanchuan** [comment]
> 参考下之前的 [issue](https://github.com/jumpserver/jumpserver/issues/10005)

必须要再发布机里面手动启动 tinkerd 服务么？？？

**Comment by LeeEirc** [comment]
主要通过类似的方式排查下问题

**Comment by fengmikaelson** [comment]
解决了么？同样的问题卡主了。
之前的issue也参考了，解决不了

**Comment by BaiJiangJie** [comment]
最新版本已优化。

**Comment by neoworkshop** [comment]
I also stuck at here.  The environment is JumpServer Community version GPLv3 v4.0.1 and windows server dc 2019.  is there any solution? or the issue was still not resolved in v4
logs as below.
TASK [Stop Tinker before install] **********************************************
2024-08-22 14:12:28 ok: [RemoteApp_Machine01]
2024-08-22 14:12:28
TASK [Download JumpServer Tinker installer] ************************************
2024-08-22 14:12:32 fatal: [RemoteApp_Machine01]: FAILED! => {"changed": false, "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.6.exe", "elapsed": 2.8437509, "msg": "Error downloading 'http://192.168.153.139/download/applets/Tinker_Installer_v0.1.6.exe' to 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.6.exe': The remote server returned an error: (404) Not Found.", "status_code": 404, "url": "http://192.168.153.139/download/applets/Tinker_Installer_v0.1.6.exe"}
2024-08-22 14:12:32
TASK [debug] *******************************************************************
2024-08-22 14:12:32 ok: [RemoteApp_Machine01] => {
    "ansible_failed_result": {
        "changed": false,
        "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.6.exe",
        "elapsed": 2.8437509,
        "failed": true,
        "invocation": {
            "module_args": {
                "checksum": null,
                "checksum_algorithm": "sha1",
                "checksum_url": null,
                "client_cert": null,
                "client_cert_password": null,
                "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.6.exe",
                "follow_redirects": "safe",
                "force": true,
                "force_basic_auth": false,
                "headers": null,
                "http_agent": "ansible-httpget",
                "maximum_redirection": 50,
                "proxy_password": null,
                "proxy_url": null,
                "proxy_use_default_credential": false,
                "proxy_username": null,
                "url": "http://192.168.153.139/download/applets/Tinker_Installer_v0.1.6.exe",
                "url_method": null,
                "url_password": null,
                "url_timeout": 30,
                "url_username": null,
                "use_default_credential": false,
                "use_proxy": true,
                "validate_certs": false
            }
        },
        "msg": "Error downloading 'http://192.168.153.139/download/applets/Tinker_Installer_v0.1.6.exe' to 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.6.exe': The remote server returned an error: (404) Not Found.",
        "status_code": 404,
        "url": "http://192.168.153.139/download/applets/Tinker_Installer_v0.1.6.exe"
    }
}
2024-08-22 14:12:32
TASK [fail] ********************************************************************
2024-08-22 14:12:32 fatal: [RemoteApp_Machine01]: FAILED! => {"changed": false, "msg": "Failed to deploy applet host"}
2024-08-22 14:12:32

**Comment by SamourM** [comment]
Hi, I am still facing same issue above i checked this as well https://github.com/jumpserver/jumpserver/issues/10005, but no luck, was this resolved?? i am already using latest 4.10.3 version and still facing the same issue: 

`        "msg": "unexpected rc from 'C:\\Users\\msamour\\AppData\\Local\\Temp\\Tinker_Installer_v0.2.2.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART': see rc, stdout, and stderr for more details",
        "rc": 5,
        "reboot_required": false,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "",
        "stdout_lines": []
    }
}
2025-07-15 16:24:22
TASK [fail] ********************************************************************
2025-07-15 16:24:22 fatal: [msamour]: FAILED! => {"changed": false, "msg": "Failed to deploy applet host"}`

Tried to run tinkerd manually on windows but it asks for a token and in community edition i dont see anywhere to generate token im assuming it is auto generated somehow so we dont need  to manually register it.

Also, it does not make sense to install tinkerd manually to fix the issue the remote app UI should handle it, i dont need to login to the server powershell and play with it.

As i see "rc" error, i thinks there is issue with the permission of the folders, but i am using Temp folder and got same issue. Please advise.
