### ISSUE TITLE
[Question] DOMAINS Issue

### ISSUE THREAD

**Issue by APK-PAM** [jumpserver/jumpserver#14329]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 20.04

### 🤔 Question Description

Hello, I have problem in login page
when i want to login i faced with this error: 

Configuration file has problems and cannot be logged in. Please contact the administrator or view latest docs
If you are administrator, you can update the config resolve it, set
DOMAINS=pam.local.net

i set the domains in config file but it still does not work. why?

**Comment by BaiJiangJie** [comment]
For version 3.6, for security reasons, it is mandatory to configure trusted domain names in the DOMAINS setting to access the service. Otherwise, an error code 400/403 will be prompted, preventing access to the page. The DOMAINS configuration is as follows:
- If the server was installed using the one-click installation and the previous version was already using JumpServer with HTTPS enabled, no changes are required.
- In scenarios where you need to access JumpServer using an IP address, you can fill in the DOMAINS field in the config.txt configuration file with either the public or internal IP, depending on your IP type.

```
# Open the config.txt configuration file and define the DOMAINS field
vim /opt/jumpserver/config/config.txt 

# Trusted DOMAINS definition
# Define trusted access IPs. Please modify according to actual circumstances. If it is a public IP, replace it with the corresponding public IP.
# DOMAINS="demo.jumpserver.org"    # Use domain name for access
# DOMAINS="172.17.200.191"         # Use IP for access
# DOMAINS="demo.jumpserver.org,172.17.200.191"    # Use both IP and domain name for access
DOMAINS=

# 重启 JumpServer 服务生效
jmsctl restart
```

**A service restart is required for the configuration to take effect.**

**Comment by BaiJiangJie** [comment]
But, If you are using one-click deployment, you need to pass the DOMAINS=pam.local.net parameter using the -e option when restarting the container.

**Comment by APK-PAM** [comment]
Hi, resolved
Thanks

**Comment by 7Eric9** [comment]
> But, If you are using one-click deployment, you need to pass the DOMAINS=pam.local.net parameter using the -e option when restarting the container.

Is it possible a way that we can skip this check, like DOMAINS="*" ?
