### ISSUE TITLE
设置完smtp,测试邮件发送成功,关掉浏览器界面.所有配置项丢失.

### ISSUE THREAD

**Issue by j14ncn** [jumpserver/jumpserver#2568]
[简述你的问题]
仪表盘  -系统设置 -邮件设置 设置完smtp,测试邮件发送成功,关掉浏览器界面.所有配置项丢失.
##### 使用版本
安装方式:阿里云服务器极速安装

Version 1.4.9-2
##### 问题复现步骤
1. [步骤1]
仪表盘  -系统设置 -邮件设置 设置完smtp. 关闭浏览器
2. [步骤2]
重启打开浏览器 所有配置项目丢失.
##### 具体表现[截图可能会更好些,最好能截全]
测试成功的截图
![image](https://user-images.githubusercontent.com/19720226/55385663-34a59900-5560-11e9-99f3-c5d91669f20c.png)
关闭浏览器后,所有配置项丢失
![image](https://user-images.githubusercontent.com/19720226/55385630-1e97d880-5560-11e9-8637-40254d7c82a0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@j14ncn 正常，测试后需要保存

**Comment by j14ncn** [comment]
> @j14ncn 正常，测试后需要保存

已经保存了,保存后关闭浏览器.依然会出现这种情况. 今天我配置了两次 都丢失了

**Comment by wojiushixiaobai** [comment]
@j14ncn 我没理解你说的丢配置是丢什么配置?

**Comment by j14ncn** [comment]
@wojiushixiaobai 就是配置的smtp信息.保存后.关了浏览器重新登录又变回smtp.jumpserver.org了.
smtp信息是存在配置文件?还是数据库?

**Comment by jincheng-xiaosu** [comment]
好像需要重启服务？发自我的华为手机-------- 原始邮件 --------主题：Re: [jumpserver/jumpserver] 设置完smtp,测试邮件发送成功,关掉浏览器界面.所有配置项丢失. (#2568)发件人：j14ncn 收件人：jumpserver/jumpserver 抄送：Subscribed @wojiushixiaobai 就是配置的smtp信息.保存后.关了浏览器重新登录又变回smtp.jumpserver.org了.

smtp信息是存在配置文件?还是数据库?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jumpserver/jumpserver","title":"jumpserver/jumpserver","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jumpserver/jumpserver"}},"updates":{"snippets":[{"icon":"PERSON","message":"@j14ncn in #2568: @wojiushixiaobai 就是配置的smtp信息.保存后.关了浏览器重新登录又变回smtp.jumpserver.org了.\r\nsmtp信息是存在配置文件?还是数据库?"}],"action":{"name":"View Issue","url":"https://github.com/jumpserver/jumpserver/issues/2568#issuecomment-479357193"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jumpserver/jumpserver/issues/2568#issuecomment-479357193",

"url": "https://github.com/jumpserver/jumpserver/issues/2568#issuecomment-479357193",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by tgyday** [comment]
这个问题现在我也遇到, 版本1.4.9-2 , 不过怀疑是显示问题, 当我点击[SMTP端口]编辑后,再点击旁边的[LDAP设置]再点回来就看到原来的设置了

**Comment by tgyday** [comment]
更新一下，重启服务后，原来的邮件设置也不见了~~

**Comment by wojiushixiaobai** [comment]
@j14ncn 暂无法复现，请检查下是否操作有误

**Comment by j14ncn** [comment]
@wojiushixiaobai 
安装方式:阿里云服务器极速安装,
请问下smtp配置完后,配置信息是在db里面,还是配置文件.我可以去看下.

**Comment by wojiushixiaobai** [comment]
@j14ncn 数据库和redis里，请检查下。

**Comment by Rsyncy** [comment]
我这边使用 "smtp.163.com" 默认 SMTP端口 25 进行测试也会出现 "测试连接" 是正常发送 test 邮件,但是点击 "提交" 之后,重新刷新浏览器之后有还原回原来默认的 邮件设置;

后续我勾选 "使用SSL",SMTP端口修改为 465 后,测试连接正常,提交后刷新浏览器也没有变回默认 邮件设置,之后发送邮件也正常了.
