### ISSUE TITLE
[v3.0 beta] tornado数据库连接bug

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#57]
bug现象: 一段时间后web terminal 无法连接，web terminal每连接一次数据库连接加1，连接断开不减少
bug描述：
1. tornado websocket下数据库连接超时关闭
2. 数据库连接一直再增加
3. connect.py卡住于此可能相关

**Comment by kid143** [comment]
这个应该是没有在request后处理数据库连接导致的。websocket这一端也采用了django的orm，但是django会在每个请求后回收数据库连接，这一机制的实现采用了django的signal设计。而在tornado的request中，并没有触发这些signal的操作，所以数据库连接会持续存在至timeout也不会被回收。具体请参考：[Django Signals](https://docs.djangoproject.com/es/1.9/topics/signals/)  

与本issue相关的两个signal分别是`request_started`和`request_finished`

English version of this post:
This issued is caused by inproperly mixed use of Tornado and Django frameworks. Since the authentication part of the websocket module is implemented through Django's ORM, in Django itself, the connections will be closed after each request. This is done by triggering corresponding signals in Django, while the tornado view does not contain such actions. So the connections remained untreated even if it is outdated. For more detail, please refer: [Django Signals](https://docs.djangoproject.com/es/1.9/topics/signals/)

**Comment by kid143** [comment]
已尝试修复在此commit: e886b55727933d92213cc38dedde8db142c925f8.

Tried to fix this promlem in commit e886b55727933d92213cc38dedde8db142c925f8 .

**Comment by ibuler** [comment]
fixed
