### ISSUE TITLE
Could you please add French language ?

### ISSUE THREAD

**Issue by troublestarter** [jumpserver/jumpserver#9752]
Hi

Could you please add French language ?

For french language working, we need to set actually ENGLISH language in the Windows servers.

Thanks you.

**Comment by ibuler** [comment]
Sorry, none of our colleagues are familiar with French at present, perhaps waiting for the time to mature, some community friends to contribute

**Comment by troublestarter** [comment]
Not possible only for keyboard ?

**Comment by BaiJiangJie** [comment]
> Hi
> 
> Could you please add French language ?
> 
> For french language working, we need to set actually ENGLISH language in the Windows servers.
> 
> Thanks you.

What does that mean for **keyboard**?

**Comment by troublestarter** [comment]
My PC is French language.
In luna i must set ENGLISH on remote server to have proper mapping with my French Keyboard actually.

**Comment by BaiJiangJie** [comment]
Oh, I get it.

I don't think the keyboard matching issue has anything to do with whether the product supports French.

What is the default language on the remote server?

**Comment by troublestarter** [comment]
My keyboard is in French and the remote server is French by default.
I must set to english for this to work actually.

Thanks you.

**Comment by BaiJiangJie** [comment]
Oh, probably the problem is known.

The reason is that when the Lion component establishes a connection with the remote server, it does not pass the keyboard parameter. 

`en-us-qwerty` connection is used by default.

In the future（**v3.3 version**）, we will add a keyboard layout drop-down option on the `Luna page -> Setting -> GUI -> GUI Setting`.
At that time, you can configure it so that you don't need to switch languages for each remote server when connecting to them.

![image](https://user-images.githubusercontent.com/32935519/229106079-7f1bc725-1a99-45fb-a952-fc0e063a4cab.png)

<img width="2139" alt="image" src="https://user-images.githubusercontent.com/32935519/229105368-48745874-668e-47bf-8f74-317dac64cb04.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/32935519/229105461-f1169622-9ed0-47de-a895-374b3042700a.png">

Such as:

![image](https://user-images.githubusercontent.com/32935519/229105509-9cc29d5a-65d8-4104-859e-f5804a917ca5.png)

**Comment by BaiJiangJie** [comment]
After the function is launched, it will reply in the current Issue.

**Comment by BaiJiangJie** [comment]
The v3.4 version is already supported.

See https://github.com/jumpserver/jumpserver/issues/10158

**Comment by BaiJiangJie** [comment]
v3.3.1 has been released, you can try it out. @troublestarter

**Comment by troublestarter** [comment]
Seems working good.

**Comment by lberrezoug** [comment]
> v3.3.1 has been released, you can try it out. @troublestarter

Hi,
wanted to bring to your attention the issue with the French keyboard layout. Unfortunately, I am unable to input special characters such as '#' or '@,' which is quite inconvenient when entering the password for connecting to a Windows session, for example. This problem seems to persist whether my JumpServer profile or the workstation is configured with the French (AZERTY) keyboard layout.

Thank you for your attention to this issue, and I hope it will be resolved soon.

JumServer v3.9.2

**Comment by rmoula** [comment]
It seems that i'm not the only one facing the special characters when working on a machine that has AZERTY key board .
Please consider fixing the situation  .
Btw i'm using JumpServer 3.9.2

**Comment by BaiJiangJie** [comment]
I would like to know on which page I enter `@` and `#`.
What characters will actually be converted to?

**Comment by rmoula** [comment]
Hi,
I hope this message finds you well. I wanted to inform you that the issue I have been experiencing still persists even after the recent update.

I appreciate the efforts and time you have invested so far in addressing this matter, and I am available to provide additional information if needed.  If you require specific details or actions on my part to better understand the problem, please feel free to let me know.

Best regards,

**Comment by BaiJiangJie** [comment]
The latest version（v3.10.1） has been fixed. It is recommended to upgrade to the latest version for use. If the problem still exists, please reopen the issue.

@rmoula
